function createfigure_2_rzad(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 21-Oct-2023 20:35:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.136467889908257 0.119782608695652 0.775 0.815]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','model');

% Create plot
plot(X2,Y2,'DisplayName','punkty pomiarowe','Marker','x','LineStyle','none');

% Create ylabel
ylabel('h(t) [V]');

% Create xlabel
xlabel('t [ms]');

% Create title
title({'Odpowiedź skokowa układu II rzędu'});

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XTickLabel',...
    {'0','0,5','1','1,5','2','2,5','3','3,5','4','4,5','5'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.661506119266791 0.618974967046568 0.215596325592984 0.0767326712018193]);

