function createfigure(Ts1, Ys1, T1, Y1)
%CREATEFIGURE(Ts1, Ys1, T1, Y1)
%  TS1:  vector of plot x data
%  YS1:  vector of plot y data
%  T1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 21-Oct-2023 19:59:16

% Create figure
figure1 = figure('PaperSize',[20.99999864 29.69999902]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Ts1,Ys1,'DisplayName','model','ZDataSource','');

% Create plot
plot(T1,Y1,'DisplayName','punkty pomiarowe','Marker','o','LineStyle','none',...
    'ZDataSource','');

% Create ylabel
ylabel({'Amplituda odpowiedzi','[V]'});

% Create xlabel
xlabel('Czas [ms]');

% Create title
title('Odpowiedź skokowa układu I rzędu');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.648682338249023 0.773319460216142 0.217592587866993 0.0935613656907494]);

